(function(){
const sizes=['F','XS','S','M','L','XL','S/M','M/L'];
const categories=[['robes','Robes'],['hauts','Hauts'],['chemises','Chemises'],['pulls','Pulls & gilets'],['vestes','Vestes'],['manteaux','Manteaux'],['pantalons','Pantalons'],['jeans','Jeans'],['jupes','Jupes'],['shorts','Shorts'],['combinaisons','Combinaisons'],['ensembles','Ensembles'],['accessoires','Accessoires'],['autres','Autres']];
const labels=Object.fromEntries(categories),icons={robes:'👗',hauts:'👚',chemises:'👔',pulls:'🧶',vestes:'🧥',manteaux:'🧥',pantalons:'👖',jeans:'👖',jupes:'👗',shorts:'🩳',combinaisons:'👗',ensembles:'🧵',accessoires:'👜',autres:'✦'};
let products=[],settings={},orders=[],editing=null;
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(message){const el=$('#onlineToast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2800)}
function errorMessage(error){try{const parsed=JSON.parse(error.message);return parsed.message||parsed.msg||error.message}catch(_){return error.message||'操作失败'}}
function productStock(product){return Array.isArray(product.variants)&&product.variants.length?product.variants.reduce((sum,v)=>sum+(Number(v.quantity)||0),0):Number(product.stock)||0}
function switchView(name){document.querySelectorAll('.admin-view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));document.querySelectorAll('.sidebar nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name))}
async function loadAll(){[products,settings,orders]=await Promise.all([CloudAPI.loadProducts(true),CloudAPI.loadSettings(true),CloudAPI.loadOrders()]);renderProducts();fillSettings();renderOrders()}
async function start(){$('#loginView')?.remove();$('#onlineApp').hidden=false;ensureCatalogueFilters();ensureOnlineImport();ensureOrderExportControls();await loadAll();setInterval(async()=>{if($('#productDialog').open||$('#onlineImportDialog')?.open)return;try{products=await CloudAPI.loadProducts(true);orders=await CloudAPI.loadOrders();renderProducts();renderOrders()}catch(_){}},20000)}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';if(!CloudAPI.configured){$('#loginError').textContent='云端项目尚未配置，请先完成 Supabase 设置。';return}try{const data=new FormData(event.target);await CloudAPI.login(data.get('email'),data.get('password'));await start()}catch(error){$('#loginError').textContent='登录失败：'+errorMessage(error)}});
start().catch(error=>{const message=$('#loginError');if(message)message.textContent='后台加载失败：'+errorMessage(error)});
$('#logoutButton').addEventListener('click',()=>location.reload());
document.querySelectorAll('.sidebar nav button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
function renderProducts(){
  const visible=products.filter(p=>p.visible!==false),total=products.reduce((sum,p)=>sum+productStock(p),0),low=products.filter(p=>productStock(p)<3).length,sold=products.filter(p=>productStock(p)===0).length;
  $('#statsGrid').innerHTML=[['在售商品',visible.length],['总库存',total],['低库存',low],['已售罄',sold]].map(([label,value])=>`<article class="stat-card"><span>${label}</span><strong>${value}</strong></article>`).join('');
  const query=$('#productSearch').value.trim().toLowerCase(),category=$('#categoryFilter')?.value||'all',status=$('#statusFilter')?.value||'all',stockFilter=$('#stockFilter')?.value||'all';const rows=products.filter(p=>{const stock=productStock(p),matchesSearch=!query||`${p.id} ${p.name} ${p.category} ${(p.variants||[]).map(v=>v.color).join(' ')}`.toLowerCase().includes(query),matchesCategory=category==='all'||p.category===category,matchesStatus=status==='all'||(status==='visible'&&p.visible!==false)||(status==='hidden'&&p.visible===false),matchesStock=stockFilter==='all'||(stockFilter==='in'&&stock>0)||(stockFilter==='low'&&stock>0&&stock<3)||(stockFilter==='out'&&stock===0);return matchesSearch&&matchesCategory&&matchesStatus&&matchesStock});
  $('#productRows').innerHTML=rows.map(product=>`<tr><td><div class="product-cell">${product.image?`<img src="${esc(product.image)}" alt="">`:`<span class="product-placeholder">${esc(product.icon)}</span>`}<div><strong>${esc(product.name)}</strong><small>${esc(product.id)}</small></div></div></td><td>${esc(product.label||labels[product.category])}</td><td><strong>${Number(product.price).toFixed(2).replace('.',',')} €</strong> <del>${Number(product.original).toFixed(2).replace('.',',')} €</del></td><td><strong>${productStock(product)}</strong><small>${product.variants?.length||0} 个颜色尺码</small></td><td><span class="pill ${product.visible?'':'off'}">${product.visible?'在售':'下架'}</span></td><td><div class="row-actions"><button data-edit="${esc(product.id)}">编辑</button><button data-delete="${esc(product.id)}">删除</button></div></td></tr>`).join('');
}
$('#productSearch').addEventListener('input',renderProducts);
function ensureCatalogueFilters(){const search=$('#productSearch');if(!search||$('#categoryFilter'))return;const wrap=document.createElement('div');wrap.className='catalogue-filters';search.parentElement.appendChild(wrap);wrap.appendChild(search);const category=document.createElement('select');category.id='categoryFilter';category.setAttribute('aria-label','按品类筛选');category.innerHTML='<option value="all">全部品类</option>'+categories.map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('');const status=document.createElement('select');status.id='statusFilter';status.setAttribute('aria-label','按状态筛选');status.innerHTML='<option value="all">全部状态</option><option value="visible">在售</option><option value="hidden">已下架</option>';const stock=document.createElement('select');stock.id='stockFilter';stock.setAttribute('aria-label','按库存筛选');stock.innerHTML='<option value="all">全部库存</option><option value="in">有库存</option><option value="low">低库存（1–2）</option><option value="out">已售罄</option>';wrap.append(category,status,stock);[category,status,stock].forEach(select=>select.addEventListener('change',renderProducts))}
let importRecords=[];
function safeImportImage(value){const text=String(value??'').trim();return /^(data:image\/(?:png|jpe?g|webp);base64,|https?:\/\/)/i.test(text)?text:''}
function ensureOnlineImport(){const add=$('#addProduct');if(!add||$('#onlineImportButton'))return;const button=document.createElement('button');button.id='onlineImportButton';button.type='button';button.className='secondary';button.textContent='Excel / PDF 入库';add.parentElement.insertBefore(button,add);button.addEventListener('click',openOnlineImport)}
function openOnlineImport(){let dialog=$('#onlineImportDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='onlineImportDialog';dialog.className='online-dialog';dialog.innerHTML='<button class="close" id="onlineImportClose" type="button">×</button><h2>Excel / PDF 批量入库</h2><p>请使用横向模板：PHOTO、CATEGORIE、COMPOSITION、REFERENCE、COULEUR、F、XS、S、M、L、XL、S/M、M/L、QTE TOTAL、PRIX、REMISE。</p><p class="import-help">商品照片必须直接插入 Excel 的 PHOTO 列对应行，不能只填写电脑本地路径。系统会读取内嵌图片并上传到商品图片库。</p><div class="import-toolbar"><button class="secondary" id="onlineImportTemplate" type="button">下载 Excel 模板</button><label>选择文件<input id="onlineImportFile" type="file" accept=".xlsx,.xls,.csv,.pdf"></label></div><div id="onlineImportLoading" hidden>正在读取文件和提取图片…</div><div id="onlineImportSummary" class="import-summary" hidden></div><div id="onlineImportMessages" class="import-messages"></div><div id="onlineImportPreview" class="table-scroll" hidden></div><div class="dialog-actions"><button class="secondary" id="onlineImportCancel" type="button">取消</button><button class="primary" id="onlineImportConfirm" type="button" disabled>确认入库</button></div>';document.body.appendChild(dialog);$('#onlineImportClose').addEventListener('click',closeOnlineImport);$('#onlineImportCancel').addEventListener('click',closeOnlineImport);$('#onlineImportFile').addEventListener('change',event=>handleOnlineImportFile(event.target.files[0]));$('#onlineImportTemplate').addEventListener('click',async()=>{try{await InventoryImport.downloadTemplate();toast('Excel 模板已下载')}catch(error){alert(errorMessage(error))}});$('#onlineImportConfirm').addEventListener('click',confirmOnlineImport)}importRecords=[];$('#onlineImportFile').value='';$('#onlineImportSummary').hidden=true;$('#onlineImportPreview').hidden=true;$('#onlineImportMessages').innerHTML='';$('#onlineImportConfirm').disabled=true;dialog.showModal()}
function closeOnlineImport(){const dialog=$('#onlineImportDialog');if(dialog?.open)dialog.close()}
function renderOnlineImport(result){const summary=$('#onlineImportSummary'),messages=$('#onlineImportMessages'),preview=$('#onlineImportPreview');summary.innerHTML=`有效规格：<strong>${result.records.length}</strong>　款号：<strong>${new Set(result.records.map(row=>row.sku)).size}</strong>　库存合计：<strong>${result.records.reduce((sum,row)=>sum+row.quantity,0)}</strong>　错误：<strong>${result.errors.length}</strong>`;summary.hidden=false;messages.innerHTML=[...result.errors.slice(0,30).map(message=>`<div class="message-error">× ${esc(message)}</div>`),...result.warnings.map(message=>`<div class="message-warning">! ${esc(message)}</div>`),!result.errors.length&&!result.warnings.length?'<div class="message-ok">✓ 数据检查通过，可以入库。</div>':''].join('');preview.innerHTML=result.records.slice(0,50).map(row=>`<div class="import-preview-row"><span>${safeImportImage(row.image)?`<img src="${esc(row.image)}" alt="">`:'—'}</span><strong>${esc(row.sku)}</strong><span>${esc(labels[row.category]||row.category)}</span><span>${esc(row.color)} / ${esc(row.size)}</span><span>${row.quantity} 件</span></div>`).join('');preview.hidden=false;$('#onlineImportConfirm').disabled=!result.records.length||result.errors.length>0}
async function handleOnlineImportFile(file){if(!file)return;const loading=$('#onlineImportLoading');loading.hidden=false;$('#onlineImportConfirm').disabled=true;$('#onlineImportMessages').innerHTML='';try{if(!window.InventoryImport)throw new Error('Excel 导入组件尚未加载，请刷新页面重试');const matrix=await InventoryImport.parseFile(file),result=InventoryImport.normalize(matrix),prices=new Map();result.records.forEach(row=>{const signature=`${row.original}|${row.discount}`;if(!prices.has(row.sku))prices.set(row.sku,signature);else if(prices.get(row.sku)!==signature)result.errors.push(`款号 ${row.sku} 存在不同价格或折扣，请统一后重新导入。`)});importRecords=result.records;renderOnlineImport(result)}catch(error){importRecords=[];renderOnlineImport({records:[],errors:[error.message],warnings:[]})}finally{loading.hidden=true}}
function buildImportedCloudProducts(records){const groups=new Map();records.forEach(row=>{if(!groups.has(row.sku))groups.set(row.sku,{first:row,name:'',category:'autres',composition:'',variants:new Map(),colorImages:{}});const group=groups.get(row.sku),key=`${row.color.toLowerCase()}|${row.size}`;if(row.name)group.name=row.name;if(row.category&&row.category!=='autres')group.category=row.category;if(row.composition)group.composition=row.composition;if(safeImportImage(row.image))group.colorImages[row.color]=row.image;if(group.variants.has(key))group.variants.get(key).quantity+=row.quantity;else group.variants.set(key,{color:row.color,size:row.size,quantity:row.quantity})});const maxOrder=products.reduce((max,product)=>Math.max(max,Number(product.order)||0),0);let offset=0;return [...groups.values()].map(group=>{const sku=group.first.sku,existing=products.find(product=>String(product.id).toUpperCase()===sku),hasImages=Object.keys(group.colorImages).length>0,first=group.first;offset++;return{...(existing||{}),id:sku,name:group.name||existing?.name||sku,category:group.category,label:labels[group.category]||labels.autres,composition:group.composition||existing?.composition||'',original:first.original,price:first.price,discountRate:first.discount,variants:[...group.variants.values()],stock:[...group.variants.values()].reduce((sum,row)=>sum+row.quantity,0),icon:existing?.icon||icons[group.category]||icons.autres,color:existing?.color||'#b78166',desc:group.composition||existing?.desc||'Disponible en plusieurs couleurs et tailles.',visible:existing?.visible!==false,order:existing?.order??maxOrder+offset,image:hasImages?'':existing?.image||'',colorImages:hasImages?group.colorImages:(existing?.colorImages||{})}})}
async function dataUrlToFile(dataUrl,name){const response=await fetch(dataUrl),blob=await response.blob();return new File([blob],name,{type:blob.type||'image/webp'})}
async function confirmOnlineImport(){if(!importRecords.length)return;const button=$('#onlineImportConfirm');button.disabled=true;$('#onlineImportLoading').textContent='正在上传商品图片并保存库存…';$('#onlineImportLoading').hidden=false;try{const imported=buildImportedCloudProducts(importRecords);let photoCount=0;for(const product of imported){for(const [color,value] of Object.entries(product.colorImages||{})){if(!safeImportImage(value)||!value.startsWith('data:image'))continue;product.colorImages[color]=await CloudAPI.upload(await dataUrlToFile(value,`${product.id}-${color}.webp`),'products');photoCount++}if(Object.keys(product.colorImages||{}).length)product.image=product.image||Object.values(product.colorImages)[0]}await CloudAPI.upsertProducts(imported);products=await CloudAPI.loadProducts(true);renderProducts();closeOnlineImport();toast(`已导入 ${imported.length} 个款号、${importRecords.reduce((sum,row)=>sum+row.quantity,0)} 件库存${photoCount?`和 ${photoCount} 张商品图片`:''}`)}catch(error){alert(errorMessage(error));button.disabled=false}finally{$('#onlineImportLoading').hidden=true}}
$('#productRows').addEventListener('click',async event=>{const edit=event.target.dataset.edit,remove=event.target.dataset.delete;if(edit)openProduct(products.find(p=>p.id===edit));if(remove&&confirm(`确定删除款号 ${remove}？`)){try{await CloudAPI.deleteProduct(remove);products=products.filter(p=>p.id!==remove);renderProducts();toast('商品已删除')}catch(error){alert(errorMessage(error))}}});
function variantRow(color='',quantities={}){const row=document.createElement('div');row.className='variant-row';row.innerHTML=`<input class="variant-color" placeholder="颜色" value="${esc(color)}">`+sizes.map(size=>`<label><small>${size}</small><input class="variant-qty" data-size="${size}" type="number" min="0" value="${Number(quantities[size])||0}"></label>`).join('')+`<button class="remove-color" type="button">×</button>`;row.querySelector('.remove-color').addEventListener('click',()=>row.remove());return row}
function addVariantRow(color='',quantities={}){$('#variantRows').appendChild(variantRow(color,quantities))}
$('#addColor').addEventListener('click',()=>addVariantRow());
function openProduct(product){editing=product||null;const form=$('#productForm');form.reset();form.elements.category.innerHTML=categories.map(([id,label])=>`<option value="${id}">${label}</option>`).join('');form.elements.visible.checked=true;$('#variantRows').innerHTML='';if(product){form.elements.id.value=product.id;form.elements.id.readOnly=true;form.elements.name.value=product.name;form.elements.category.value=product.category;form.elements.composition.value=product.composition||'';form.elements.original.value=product.original;form.elements.price.value=product.price;form.elements.visible.checked=product.visible!==false;const byColor={};(product.variants||[]).forEach(v=>(byColor[v.color]??={})[v.size]=v.quantity);Object.entries(byColor).forEach(([color,qty])=>addVariantRow(color,qty))}else{form.elements.id.readOnly=false;addVariantRow()}$('#productDialogTitle').textContent=product?'编辑商品':'新增商品';$('#productDialog').showModal()}
$('#addProduct').addEventListener('click',()=>openProduct());$('#closeProduct').addEventListener('click',()=>$('#productDialog').close());
$('#productForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,variants=[];document.querySelectorAll('.variant-row').forEach(row=>{const color=row.querySelector('.variant-color').value.trim();if(!color)return;row.querySelectorAll('.variant-qty').forEach(input=>{const quantity=Math.max(0,Math.floor(Number(input.value)||0));if(quantity)variants.push({color,size:input.dataset.size,quantity})})});const category=form.elements.category.value,original=Number(form.elements.original.value)||0,price=Number(form.elements.price.value)||0;const product={...(editing||{}),id:form.elements.id.value.trim().toUpperCase(),name:form.elements.name.value.trim(),category,label:labels[category],composition:form.elements.composition.value.trim(),original,price,discountRate:original?Math.max(0,1-price/original):0,variants,stock:variants.reduce((sum,v)=>sum+v.quantity,0),icon:icons[category],color:'#b78166',desc:form.elements.composition.value.trim()||'Disponible en plusieurs couleurs et tailles.',visible:form.elements.visible.checked,order:editing?.order||products.length+1,image:editing?.image||'',colorImages:editing?.colorImages||{}};try{const photo=form.elements.photo.files[0];if(photo)product.image=await CloudAPI.upload(photo,'products');await CloudAPI.upsertProducts([product]);const index=products.findIndex(p=>p.id===product.id);if(index>=0)products[index]=product;else products.push(product);$('#productDialog').close();renderProducts();toast('商品已保存并同步前台')}catch(error){alert(errorMessage(error))}});
function fillSettings(){const form=$('#settingsForm');['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle','columns'].forEach(name=>{if(form.elements[name])form.elements[name].value=settings[name]??''})}
$('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,next={...settings};['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle'].forEach(name=>next[name]=form.elements[name].value.trim());next.columns=Number(form.elements.columns.value)||4;try{const logo=form.elements.logoFile.files[0],hero=form.elements.heroFile.files[0],how=form.elements.howFile.files[0];if(logo)next.logoImage=await CloudAPI.upload(logo,'site');if(hero){const url=await CloudAPI.upload(hero,'site');if(hero.type.startsWith('video/')){next.heroVideo=url;next.heroMediaType='video'}else{next.heroImage=url;next.heroMediaType='image'}}if(how)next.howBackgroundImage=await CloudAPI.upload(how,'site');await CloudAPI.saveSettings(next);settings=next;toast('页面设置已更新')}catch(error){alert(errorMessage(error))}});
const statusLabels={new:'待确认',confirmed:'已确认',done:'已完成',cancelled:'已取消'};
function orderExportRows(){return orders.map(order=>{const customer=order.customer||{},items=Array.isArray(order.items)?order.items:[],total=Number(order.total)||items.reduce((sum,i)=>sum+(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)),0);return{status:statusLabels[order.status]||order.status||'',code:order.public_code||order.id?.slice(0,8)||'',createdAt:order.created_at?new Date(order.created_at).toLocaleString('zh-CN'):'',name:customer.name||'',phone:customer.phone||'',email:customer.email||'',items:items.map(i=>`${i.name||i.id||''} / ${i.color||''} / ${i.size||''} × ${Math.max(1,Number(i.quantity)||1)} = ${(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)).toFixed(2)} €`).join('; '),total:total.toFixed(2)}})}
function renderOrders(){const fresh=orders.filter(o=>o.status==='new').length;$('#newOrderBadge').textContent=fresh;$('#orderList').innerHTML=orders.length?orders.map(order=>{const customer=order.customer||{},items=Array.isArray(order.items)?order.items:[],total=Number(order.total)||items.reduce((sum,i)=>sum+(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)),0);return `<article class="order-card"><div><span class="pill ${order.status==='cancelled'?'off':''}">${esc(statusLabels[order.status]||order.status)}</span><h3>${esc(order.public_code||order.id.slice(0,8))}</h3><small>${new Date(order.created_at).toLocaleString('zh-CN')}</small></div><div><strong>${esc(customer.name||'')}</strong> · ${esc(customer.phone||'')}<br><small>${esc(customer.email||'')}</small><p class="order-items">${items.map(i=>`${esc(i.name||i.id)} · ${esc(i.color||'')} ${esc(i.size||'')} · ${Math.max(1,Number(i.quantity)||1)} × ${Number(i.price||0).toFixed(2)} €`).join('<br>')}</p><strong>预订单总金额：${total.toFixed(2)} €</strong></div><div class="order-actions">${order.status==='new'?`<button class="primary" data-status="confirmed" data-order="${order.id}">确认并扣库存</button><button class="secondary" data-status="cancelled" data-order="${order.id}">取消</button>`:order.status==='confirmed'?`<button class="primary" data-status="done" data-order="${order.id}">完成</button>`:''}</div></article>`}).join(''):'<div class="panel" style="padding:35px">暂无客户预留。</div>'}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportOrdersExcel(){const rows=orderExportRows();if(!rows.length){toast('暂无订单可导出');return}const headers=['状态','订单号','提交时间','客户姓名','电话','邮箱','商品明细','预订单总金额 (€)'],cells=value=>`<td style="border:1px solid #999;padding:6px;vertical-align:top">${esc(value)}</td>`,html=`<html><head><meta charset="UTF-8"></head><body><table><tr>${headers.map(h=>`<th style="border:1px solid #999;padding:6px;background:#e8eee9">${esc(h)}</th>`).join('')}</tr>${rows.map(row=>`<tr>${[row.status,row.code,row.createdAt,row.name,row.phone,row.email,row.items,row.total].map(cells).join('')}</tr>`).join('')}</table></body></html>`;downloadBlob(new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8'}),`interdee-orders-${new Date().toISOString().slice(0,10)}.xls`);toast('Excel 订单文件已下载')}
function exportOrdersPdf(){const rows=orderExportRows();if(!rows.length){toast('暂无订单可导出');return}const win=window.open('','_blank','width=1200,height=800');if(!win){alert('请允许浏览器打开弹出窗口，然后再次点击导出 PDF。');return}const headers=['状态','订单号','提交时间','客户姓名','电话','邮箱','商品明细','总金额 (€)'];win.document.write(`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><title>INTERDEE 订单</title><style>body{font-family:Arial,"Microsoft YaHei",sans-serif;padding:24px;color:#17251e}h1{font-size:22px;margin:0 0 6px}p{color:#63716a;margin:0 0 18px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #b8c2bc;padding:7px;text-align:left;vertical-align:top}th{background:#e8eee9} @media print{body{padding:0}button{display:none}}</style></head><body><h1>INTERDEE · 客户订单</h1><p>导出时间：${esc(new Date().toLocaleString('zh-CN'))} · 共 ${rows.length} 单</p><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${[row.status,row.code,row.createdAt,row.name,row.phone,row.email,row.items,row.total].map(value=>`<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250));</script></body></html>`);win.document.close();win.focus();toast('已打开打印窗口，请选择“另存为 PDF”')}
function ensureOrderExportControls(){const refresh=$('#refreshOrders');if(!refresh||$('#exportOrderActions'))return;const wrap=document.createElement('div');wrap.className='order-export-actions';wrap.id='exportOrderActions';const excel=document.createElement('button');excel.className='secondary';excel.type='button';excel.textContent='导出 Excel';excel.id='exportOrdersExcel';const pdf=document.createElement('button');pdf.className='secondary';pdf.type='button';pdf.textContent='导出 PDF';pdf.id='exportOrdersPdf';wrap.append(excel,pdf);refresh.parentElement.insertBefore(wrap,refresh);excel.addEventListener('click',exportOrdersExcel);pdf.addEventListener('click',exportOrdersPdf)}
async function confirmAndDeduct(order){const changed=new Set();for(const item of order.items||[]){const product=products.find(p=>p.id===item.id);if(!product)continue;const quantity=Math.max(1,Math.floor(Number(item.quantity)||1));const variant=product.variants?.find(v=>v.color===item.color&&v.size===item.size);if(variant&&variant.quantity>0)variant.quantity=Math.max(0,variant.quantity-quantity);else if(!product.variants?.length&&product.stock>0)product.stock=Math.max(0,product.stock-quantity);product.stock=productStock(product);changed.add(product)}if(changed.size)await CloudAPI.upsertProducts([...changed])}
$('#orderList').addEventListener('click',async event=>{const id=event.target.dataset.order,status=event.target.dataset.status;if(!id||!status)return;try{const order=orders.find(o=>o.id===id);if(status==='confirmed')await confirmAndDeduct(order);await CloudAPI.updateOrder(id,status);order.status=status;renderProducts();renderOrders();toast('订单状态已更新')}catch(error){alert(errorMessage(error))}});
$('#refreshOrders').addEventListener('click',async()=>{orders=await CloudAPI.loadOrders();renderOrders();toast('订单已刷新')});
})();
