(function(){
const sizes=['F','XS','S','M','L','XL','S/M','M/L'];
const categories=[['robes','Robes'],['hauts','Hauts'],['chemises','Chemises'],['pulls','Pulls & gilets'],['vestes','Vestes'],['manteaux','Manteaux'],['pantalons','Pantalons'],['jeans','Jeans'],['jupes','Jupes'],['shorts','Shorts'],['combinaisons','Combinaisons'],['ensembles','Ensembles'],['accessoires','Accessoires'],['autres','Autres']];
const labels=Object.fromEntries(categories),icons={robes:'👗',hauts:'👚',chemises:'👔',pulls:'🧶',vestes:'🧥',manteaux:'🧥',pantalons:'👖',jeans:'👖',jupes:'👗',shorts:'🩳',combinaisons:'👗',ensembles:'🧵',accessoires:'👜',autres:'✦'};
let products=[],settings={},orders=[],editing=null;
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(message){const el=$('#onlineToast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2800)}
function errorMessage(error){try{const parsed=JSON.parse(error.message);return parsed.message||parsed.msg||error.message}catch(_){return error.message||'操作失败'}}
function productStock(product){return Array.isArray(product.variants)&&product.variants.length?product.variants.reduce((sum,v)=>sum+(Number(v.quantity)||0),0):Number(product.stock)||0}
function switchView(name){document.querySelectorAll('.admin-view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));document.querySelectorAll('.sidebar nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name))}
async function loadAll(){[products,settings,orders]=await Promise.all([CloudAPI.loadProducts(true),CloudAPI.loadSettings(true),CloudAPI.loadOrders()]);renderProducts();fillSettings();renderOrders()}
async function start(){await CloudAPI.verifyAdmin();$('#loginView').hidden=true;$('#onlineApp').hidden=false;await loadAll();setInterval(async()=>{if($('#productDialog').open)return;try{products=await CloudAPI.loadProducts(true);orders=await CloudAPI.loadOrders();renderProducts();renderOrders()}catch(_){}},20000)}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';if(!CloudAPI.configured){$('#loginError').textContent='云端项目尚未配置，请先完成 Supabase 设置。';return}try{const data=new FormData(event.target);await CloudAPI.login(data.get('email'),data.get('password'));await start()}catch(error){$('#loginError').textContent='登录失败：'+errorMessage(error)}});
if(CloudAPI.configured&&sessionStorage.getItem('interdeeAdminTokenV1'))start().catch(()=>CloudAPI.logout());
$('#logoutButton').addEventListener('click',()=>{CloudAPI.logout();location.reload()});
document.querySelectorAll('.sidebar nav button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
function renderProducts(){
  const visible=products.filter(p=>p.visible!==false),total=products.reduce((sum,p)=>sum+productStock(p),0),low=products.filter(p=>productStock(p)<3).length,sold=products.filter(p=>productStock(p)===0).length;
  $('#statsGrid').innerHTML=[['在售商品',visible.length],['总库存',total],['低库存',low],['已售罄',sold]].map(([label,value])=>`<article class="stat-card"><span>${label}</span><strong>${value}</strong></article>`).join('');
  const query=$('#productSearch').value.trim().toLowerCase();const rows=products.filter(p=>!query||`${p.id} ${p.name} ${p.category} ${(p.variants||[]).map(v=>v.color).join(' ')}`.toLowerCase().includes(query));
  $('#productRows').innerHTML=rows.map(product=>`<tr><td><div class="product-cell">${product.image?`<img src="${esc(product.image)}" alt="">`:`<span class="product-placeholder">${esc(product.icon)}</span>`}<div><strong>${esc(product.name)}</strong><small>${esc(product.id)}</small></div></div></td><td>${esc(product.label||labels[product.category])}</td><td><strong>${Number(product.price).toFixed(2).replace('.',',')} €</strong> <del>${Number(product.original).toFixed(2).replace('.',',')} €</del></td><td><strong>${productStock(product)}</strong><small>${product.variants?.length||0} 个颜色尺码</small></td><td><span class="pill ${product.visible?'':'off'}">${product.visible?'在售':'下架'}</span></td><td><div class="row-actions"><button data-edit="${esc(product.id)}">编辑</button><button data-delete="${esc(product.id)}">删除</button></div></td></tr>`).join('');
}
$('#productSearch').addEventListener('input',renderProducts);
$('#productRows').addEventListener('click',async event=>{const edit=event.target.dataset.edit,remove=event.target.dataset.delete;if(edit)openProduct(products.find(p=>p.id===edit));if(remove&&confirm(`确定删除款号 ${remove}？`)){try{await CloudAPI.deleteProduct(remove);products=products.filter(p=>p.id!==remove);renderProducts();toast('商品已删除')}catch(error){alert(errorMessage(error))}}});
function variantRow(color='',quantities={}){const row=document.createElement('div');row.className='variant-row';row.innerHTML=`<input class="variant-color" placeholder="颜色" value="${esc(color)}">`+sizes.map(size=>`<label><small>${size}</small><input class="variant-qty" data-size="${size}" type="number" min="0" value="${Number(quantities[size])||0}"></label>`).join('')+`<button class="remove-color" type="button">×</button>`;row.querySelector('.remove-color').addEventListener('click',()=>row.remove());return row}
function addVariantRow(color='',quantities={}){$('#variantRows').appendChild(variantRow(color,quantities))}
$('#addColor').addEventListener('click',()=>addVariantRow());
function openProduct(product){editing=product||null;const form=$('#productForm');form.reset();form.elements.category.innerHTML=categories.map(([id,label])=>`<option value="${id}">${label}</option>`).join('');form.elements.visible.checked=true;$('#variantRows').innerHTML='';if(product){form.elements.id.value=product.id;form.elements.id.readOnly=true;form.elements.name.value=product.name;form.elements.category.value=product.category;form.elements.composition.value=product.composition||'';form.elements.original.value=product.original;form.elements.price.value=product.price;form.elements.visible.checked=product.visible!==false;const byColor={};(product.variants||[]).forEach(v=>(byColor[v.color]??={})[v.size]=v.quantity);Object.entries(byColor).forEach(([color,qty])=>addVariantRow(color,qty))}else{form.elements.id.readOnly=false;addVariantRow()}$('#productDialogTitle').textContent=product?'编辑商品':'新增商品';$('#productDialog').showModal()}
$('#addProduct').addEventListener('click',()=>openProduct());$('#closeProduct').addEventListener('click',()=>$('#productDialog').close());
$('#productForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,variants=[];document.querySelectorAll('.variant-row').forEach(row=>{const color=row.querySelector('.variant-color').value.trim();if(!color)return;row.querySelectorAll('.variant-qty').forEach(input=>{const quantity=Math.max(0,Math.floor(Number(input.value)||0));if(quantity)variants.push({color,size:input.dataset.size,quantity})})});const category=form.elements.category.value,original=Number(form.elements.original.value)||0,price=Number(form.elements.price.value)||0;const product={...(editing||{}),id:form.elements.id.value.trim().toUpperCase(),name:form.elements.name.value.trim(),category,label:labels[category],composition:form.elements.composition.value.trim(),original,price,discountRate:original?Math.max(0,1-price/original):0,variants,stock:variants.reduce((sum,v)=>sum+v.quantity,0),icon:icons[category],color:'#b78166',desc:form.elements.composition.value.trim()||'Disponible en plusieurs couleurs et tailles.',visible:form.elements.visible.checked,order:editing?.order||products.length+1,image:editing?.image||'',colorImages:editing?.colorImages||{}};try{const photo=form.elements.photo.files[0];if(photo)product.image=await CloudAPI.upload(photo,'products');await CloudAPI.upsertProducts([product]);const index=products.findIndex(p=>p.id===product.id);if(index>=0)products[index]=product;else products.push(product);$('#productDialog').close();renderProducts();toast('商品已保存并同步前台')}catch(error){alert(errorMessage(error))}});
function fillSettings(){const form=$('#settingsForm');['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle','columns'].forEach(name=>{if(form.elements[name])form.elements[name].value=settings[name]??''})}
$('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,next={...settings};['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle'].forEach(name=>next[name]=form.elements[name].value.trim());next.columns=Number(form.elements.columns.value)||4;try{const logo=form.elements.logoFile.files[0],hero=form.elements.heroFile.files[0],how=form.elements.howFile.files[0];if(logo)next.logoImage=await CloudAPI.upload(logo,'site');if(hero){const url=await CloudAPI.upload(hero,'site');if(hero.type.startsWith('video/')){next.heroVideo=url;next.heroMediaType='video'}else{next.heroImage=url;next.heroMediaType='image'}}if(how)next.howBackgroundImage=await CloudAPI.upload(how,'site');await CloudAPI.saveSettings(next);settings=next;toast('页面设置已更新')}catch(error){alert(errorMessage(error))}});
function renderOrders(){const fresh=orders.filter(o=>o.status==='new').length;$('#newOrderBadge').textContent=fresh;$('#orderList').innerHTML=orders.length?orders.map(order=>{const customer=order.customer||{},items=Array.isArray(order.items)?order.items:[];return `<article class="order-card"><div><span class="pill ${order.status==='cancelled'?'off':''}">${esc(order.status)}</span><h3>${esc(order.public_code||order.id.slice(0,8))}</h3><small>${new Date(order.created_at).toLocaleString('zh-CN')}</small></div><div><strong>${esc(customer.name||'')}</strong> · ${esc(customer.phone||'')}<br><small>${esc(customer.email||'')}</small><p class="order-items">${items.map(i=>`${esc(i.name||i.id)} · ${esc(i.color||'')} ${esc(i.size||'')} · ${Number(i.price).toFixed(2)} €`).join('<br>')}</p></div><div class="order-actions">${order.status==='new'?`<button class="primary" data-status="confirmed" data-order="${order.id}">确认并扣库存</button><button class="secondary" data-status="cancelled" data-order="${order.id}">取消</button>`:order.status==='confirmed'?`<button class="primary" data-status="done" data-order="${order.id}">完成</button>`:''}</div></article>`}).join(''):'<div class="panel" style="padding:35px">暂无客户预留。</div>'}
async function confirmAndDeduct(order){const changed=new Set();for(const item of order.items||[]){const product=products.find(p=>p.id===item.id);if(!product)continue;const variant=product.variants?.find(v=>v.color===item.color&&v.size===item.size);if(variant&&variant.quantity>0)variant.quantity--;else if(!product.variants?.length&&product.stock>0)product.stock--;product.stock=productStock(product);changed.add(product)}if(changed.size)await CloudAPI.upsertProducts([...changed])}
$('#orderList').addEventListener('click',async event=>{const id=event.target.dataset.order,status=event.target.dataset.status;if(!id||!status)return;try{const order=orders.find(o=>o.id===id);if(status==='confirmed')await confirmAndDeduct(order);await CloudAPI.updateOrder(id,status);order.status=status;renderProducts();renderOrders();toast('订单状态已更新')}catch(error){alert(errorMessage(error))}});
$('#refreshOrders').addEventListener('click',async()=>{orders=await CloudAPI.loadOrders();renderOrders();toast('订单已刷新')});
})();
