(function(){
const sizes=['F','XS','S','M','L','XL','S/M','M/L'];
const categories=[['robes','Robes'],['hauts','Hauts'],['chemises','Chemises'],['pulls','Pulls & gilets'],['vestes','Vestes'],['manteaux','Manteaux'],['pantalons','Pantalons'],['jeans','Jeans'],['jupes','Jupes'],['shorts','Shorts'],['combinaisons','Combinaisons'],['ensembles','Ensembles'],['accessoires','Accessoires'],['autres','Autres']];
const labels=Object.fromEntries(categories),icons={robes:'👗',hauts:'👚',chemises:'👔',pulls:'🧶',vestes:'🧥',manteaux:'🧥',pantalons:'👖',jeans:'👖',jupes:'👗',shorts:'🩳',combinaisons:'👗',ensembles:'🧵',accessoires:'👜',autres:'✦'};
let products=[],settings={},orders=[],editing=null;
const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(message){const el=$('#onlineToast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2800)}
function errorMessage(error){try{const parsed=JSON.parse(error.message);return parsed.message||parsed.msg||error.message}catch(_){return error.message||'操作失败'}}
function productStock(product){return Array.isArray(product.variants)&&product.variants.length?product.variants.reduce((sum,v)=>sum+(Number(v.quantity)||0),0):Number(product.stock)||0}
function switchView(name){document.querySelectorAll('.admin-view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));document.querySelectorAll('.sidebar nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name))}
async function loadAll(){[products,settings,orders]=await Promise.all([CloudAPI.loadProducts(true),CloudAPI.loadSettings(true),CloudAPI.loadOrders()]);renderProducts();fillSettings();renderOrders()}
async function start(){$('#loginView')?.remove();$('#onlineApp').hidden=false;ensureCatalogueFilters();ensureOrderExportControls();await loadAll();setInterval(async()=>{if($('#productDialog').open)return;try{products=await CloudAPI.loadProducts(true);orders=await CloudAPI.loadOrders();renderProducts();renderOrders()}catch(_){}},20000)}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();$('#loginError').textContent='';if(!CloudAPI.configured){$('#loginError').textContent='云端项目尚未配置，请先完成 Supabase 设置。';return}try{const data=new FormData(event.target);await CloudAPI.login(data.get('email'),data.get('password'));await start()}catch(error){$('#loginError').textContent='登录失败：'+errorMessage(error)}});
start().catch(error=>{const message=$('#loginError');if(message)message.textContent='后台加载失败：'+errorMessage(error)});
$('#logoutButton').addEventListener('click',()=>location.reload());
document.querySelectorAll('.sidebar nav button').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
function renderProducts(){
  const visible=products.filter(p=>p.visible!==false),total=products.reduce((sum,p)=>sum+productStock(p),0),low=products.filter(p=>productStock(p)<3).length,sold=products.filter(p=>productStock(p)===0).length;
  $('#statsGrid').innerHTML=[['在售商品',visible.length],['总库存',total],['低库存',low],['已售罄',sold]].map(([label,value])=>`<article class="stat-card"><span>${label}</span><strong>${value}</strong></article>`).join('');
  const query=$('#productSearch').value.trim().toLowerCase(),category=$('#categoryFilter')?.value||'all',status=$('#statusFilter')?.value||'all',stockFilter=$('#stockFilter')?.value||'all';const rows=products.filter(p=>{const stock=productStock(p),matchesSearch=!query||`${p.id} ${p.name} ${p.category} ${(p.variants||[]).map(v=>v.color).join(' ')}`.toLowerCase().includes(query),matchesCategory=category==='all'||p.category===category,matchesStatus=status==='all'||(status==='visible'&&p.visible!==false)||(status==='hidden'&&p.visible===false),matchesStock=stockFilter==='all'||(stockFilter==='in'&&stock>0)||(stockFilter==='low'&&stock>0&&stock<3)||(stockFilter==='out'&&stock===0);return matchesSearch&&matchesCategory&&matchesStatus&&matchesStock});
  $('#productRows').innerHTML=rows.map(product=>`<tr><td><div class="product-cell">${product.image?`<img src="${esc(product.image)}" alt="">`:`<span class="product-placeholder">${esc(product.icon)}</span>`}<div><strong>${esc(product.name)}</strong><small>${esc(product.id)}</small></div></div></td><td>${esc(product.label||labels[product.category])}</td><td><strong>${Number(product.price).toFixed(2).replace('.',',')} €</strong> <del>${Number(product.original).toFixed(2).replace('.',',')} €</del></td><td><strong>${productStock(product)}</strong><small>${product.variants?.length||0} 个颜色尺码</small></td><td><span class="pill ${product.visible?'':'off'}">${product.visible?'在售':'下架'}</span></td><td><div class="row-actions"><button data-edit="${esc(product.id)}">编辑</button><button data-delete="${esc(product.id)}">删除</button></div></td></tr>`).join('');
}
$('#productSearch').addEventListener('input',renderProducts);
function ensureCatalogueFilters(){const search=$('#productSearch');if(!search||$('#categoryFilter'))return;const wrap=document.createElement('div');wrap.className='catalogue-filters';search.parentElement.appendChild(wrap);wrap.appendChild(search);const category=document.createElement('select');category.id='categoryFilter';category.setAttribute('aria-label','按品类筛选');category.innerHTML='<option value="all">全部品类</option>'+categories.map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('');const status=document.createElement('select');status.id='statusFilter';status.setAttribute('aria-label','按状态筛选');status.innerHTML='<option value="all">全部状态</option><option value="visible">在售</option><option value="hidden">已下架</option>';const stock=document.createElement('select');stock.id='stockFilter';stock.setAttribute('aria-label','按库存筛选');stock.innerHTML='<option value="all">全部库存</option><option value="in">有库存</option><option value="low">低库存（1–2）</option><option value="out">已售罄</option>';wrap.append(category,status,stock);[category,status,stock].forEach(select=>select.addEventListener('change',renderProducts))}
$('#productRows').addEventListener('click',async event=>{const edit=event.target.dataset.edit,remove=event.target.dataset.delete;if(edit)openProduct(products.find(p=>p.id===edit));if(remove&&confirm(`确定删除款号 ${remove}？`)){try{await CloudAPI.deleteProduct(remove);products=products.filter(p=>p.id!==remove);renderProducts();toast('商品已删除')}catch(error){alert(errorMessage(error))}}});
function variantRow(color='',quantities={}){const row=document.createElement('div');row.className='variant-row';row.innerHTML=`<input class="variant-color" placeholder="颜色" value="${esc(color)}">`+sizes.map(size=>`<label><small>${size}</small><input class="variant-qty" data-size="${size}" type="number" min="0" value="${Number(quantities[size])||0}"></label>`).join('')+`<button class="remove-color" type="button">×</button>`;row.querySelector('.remove-color').addEventListener('click',()=>row.remove());return row}
function addVariantRow(color='',quantities={}){$('#variantRows').appendChild(variantRow(color,quantities))}
$('#addColor').addEventListener('click',()=>addVariantRow());
function openProduct(product){editing=product||null;const form=$('#productForm');form.reset();form.elements.category.innerHTML=categories.map(([id,label])=>`<option value="${id}">${label}</option>`).join('');form.elements.visible.checked=true;$('#variantRows').innerHTML='';if(product){form.elements.id.value=product.id;form.elements.id.readOnly=true;form.elements.name.value=product.name;form.elements.category.value=product.category;form.elements.composition.value=product.composition||'';form.elements.original.value=product.original;form.elements.price.value=product.price;form.elements.visible.checked=product.visible!==false;const byColor={};(product.variants||[]).forEach(v=>(byColor[v.color]??={})[v.size]=v.quantity);Object.entries(byColor).forEach(([color,qty])=>addVariantRow(color,qty))}else{form.elements.id.readOnly=false;addVariantRow()}$('#productDialogTitle').textContent=product?'编辑商品':'新增商品';$('#productDialog').showModal()}
$('#addProduct').addEventListener('click',()=>openProduct());$('#closeProduct').addEventListener('click',()=>$('#productDialog').close());
$('#productForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,variants=[];document.querySelectorAll('.variant-row').forEach(row=>{const color=row.querySelector('.variant-color').value.trim();if(!color)return;row.querySelectorAll('.variant-qty').forEach(input=>{const quantity=Math.max(0,Math.floor(Number(input.value)||0));if(quantity)variants.push({color,size:input.dataset.size,quantity})})});const category=form.elements.category.value,original=Number(form.elements.original.value)||0,price=Number(form.elements.price.value)||0;const product={...(editing||{}),id:form.elements.id.value.trim().toUpperCase(),name:form.elements.name.value.trim(),category,label:labels[category],composition:form.elements.composition.value.trim(),original,price,discountRate:original?Math.max(0,1-price/original):0,variants,stock:variants.reduce((sum,v)=>sum+v.quantity,0),icon:icons[category],color:'#b78166',desc:form.elements.composition.value.trim()||'Disponible en plusieurs couleurs et tailles.',visible:form.elements.visible.checked,order:editing?.order||products.length+1,image:editing?.image||'',colorImages:editing?.colorImages||{}};try{const photo=form.elements.photo.files[0];if(photo)product.image=await CloudAPI.upload(photo,'products');await CloudAPI.upsertProducts([product]);const index=products.findIndex(p=>p.id===product.id);if(index>=0)products[index]=product;else products.push(product);$('#productDialog').close();renderProducts();toast('商品已保存并同步前台')}catch(error){alert(errorMessage(error))}});
function fillSettings(){const form=$('#settingsForm');['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle','columns'].forEach(name=>{if(form.elements[name])form.elements[name].value=settings[name]??''})}
$('#settingsForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,next={...settings};['brandName','notice','heroTitle','heroAccent','heroDescription','sectionTitle'].forEach(name=>next[name]=form.elements[name].value.trim());next.columns=Number(form.elements.columns.value)||4;try{const logo=form.elements.logoFile.files[0],hero=form.elements.heroFile.files[0],how=form.elements.howFile.files[0];if(logo)next.logoImage=await CloudAPI.upload(logo,'site');if(hero){const url=await CloudAPI.upload(hero,'site');if(hero.type.startsWith('video/')){next.heroVideo=url;next.heroMediaType='video'}else{next.heroImage=url;next.heroMediaType='image'}}if(how)next.howBackgroundImage=await CloudAPI.upload(how,'site');await CloudAPI.saveSettings(next);settings=next;toast('页面设置已更新')}catch(error){alert(errorMessage(error))}});
const statusLabels={new:'待确认',confirmed:'已确认',done:'已完成',cancelled:'已取消'};
function orderExportRows(){return orders.map(order=>{const customer=order.customer||{},items=Array.isArray(order.items)?order.items:[],total=Number(order.total)||items.reduce((sum,i)=>sum+(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)),0);return{status:statusLabels[order.status]||order.status||'',code:order.public_code||order.id?.slice(0,8)||'',createdAt:order.created_at?new Date(order.created_at).toLocaleString('zh-CN'):'',name:customer.name||'',phone:customer.phone||'',email:customer.email||'',items:items.map(i=>`${i.name||i.id||''} / ${i.color||''} / ${i.size||''} × ${Math.max(1,Number(i.quantity)||1)} = ${(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)).toFixed(2)} €`).join('; '),total:total.toFixed(2)}})}
function renderOrders(){const fresh=orders.filter(o=>o.status==='new').length;$('#newOrderBadge').textContent=fresh;$('#orderList').innerHTML=orders.length?orders.map(order=>{const customer=order.customer||{},items=Array.isArray(order.items)?order.items:[],total=Number(order.total)||items.reduce((sum,i)=>sum+(Number(i.lineTotal)||Number(i.price||0)*Math.max(1,Number(i.quantity)||1)),0);return `<article class="order-card"><div><span class="pill ${order.status==='cancelled'?'off':''}">${esc(statusLabels[order.status]||order.status)}</span><h3>${esc(order.public_code||order.id.slice(0,8))}</h3><small>${new Date(order.created_at).toLocaleString('zh-CN')}</small></div><div><strong>${esc(customer.name||'')}</strong> · ${esc(customer.phone||'')}<br><small>${esc(customer.email||'')}</small><p class="order-items">${items.map(i=>`${esc(i.name||i.id)} · ${esc(i.color||'')} ${esc(i.size||'')} · ${Math.max(1,Number(i.quantity)||1)} × ${Number(i.price||0).toFixed(2)} €`).join('<br>')}</p><strong>预订单总金额：${total.toFixed(2)} €</strong></div><div class="order-actions">${order.status==='new'?`<button class="primary" data-status="confirmed" data-order="${order.id}">确认并扣库存</button><button class="secondary" data-status="cancelled" data-order="${order.id}">取消</button>`:order.status==='confirmed'?`<button class="primary" data-status="done" data-order="${order.id}">完成</button>`:''}</div></article>`}).join(''):'<div class="panel" style="padding:35px">暂无客户预留。</div>'}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportOrdersExcel(){const rows=orderExportRows();if(!rows.length){toast('暂无订单可导出');return}const headers=['状态','订单号','提交时间','客户姓名','电话','邮箱','商品明细','预订单总金额 (€)'],cells=value=>`<td style="border:1px solid #999;padding:6px;vertical-align:top">${esc(value)}</td>`,html=`<html><head><meta charset="UTF-8"></head><body><table><tr>${headers.map(h=>`<th style="border:1px solid #999;padding:6px;background:#e8eee9">${esc(h)}</th>`).join('')}</tr>${rows.map(row=>`<tr>${[row.status,row.code,row.createdAt,row.name,row.phone,row.email,row.items,row.total].map(cells).join('')}</tr>`).join('')}</table></body></html>`;downloadBlob(new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8'}),`interdee-orders-${new Date().toISOString().slice(0,10)}.xls`);toast('Excel 订单文件已下载')}
function exportOrdersPdf(){const rows=orderExportRows();if(!rows.length){toast('暂无订单可导出');return}const win=window.open('','_blank','width=1200,height=800');if(!win){alert('请允许浏览器打开弹出窗口，然后再次点击导出 PDF。');return}const headers=['状态','订单号','提交时间','客户姓名','电话','邮箱','商品明细','总金额 (€)'];win.document.write(`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><title>INTERDEE 订单</title><style>body{font-family:Arial,"Microsoft YaHei",sans-serif;padding:24px;color:#17251e}h1{font-size:22px;margin:0 0 6px}p{color:#63716a;margin:0 0 18px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #b8c2bc;padding:7px;text-align:left;vertical-align:top}th{background:#e8eee9} @media print{body{padding:0}button{display:none}}</style></head><body><h1>INTERDEE · 客户订单</h1><p>导出时间：${esc(new Date().toLocaleString('zh-CN'))} · 共 ${rows.length} 单</p><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${[row.status,row.code,row.createdAt,row.name,row.phone,row.email,row.items,row.total].map(value=>`<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250));</script></body></html>`);win.document.close();win.focus();toast('已打开打印窗口，请选择“另存为 PDF”')}
function ensureOrderExportControls(){const refresh=$('#refreshOrders');if(!refresh||$('#exportOrderActions'))return;const wrap=document.createElement('div');wrap.className='order-export-actions';wrap.id='exportOrderActions';const excel=document.createElement('button');excel.className='secondary';excel.type='button';excel.textContent='导出 Excel';excel.id='exportOrdersExcel';const pdf=document.createElement('button');pdf.className='secondary';pdf.type='button';pdf.textContent='导出 PDF';pdf.id='exportOrdersPdf';wrap.append(excel,pdf);refresh.parentElement.insertBefore(wrap,refresh);excel.addEventListener('click',exportOrdersExcel);pdf.addEventListener('click',exportOrdersPdf)}
async function confirmAndDeduct(order){const changed=new Set();for(const item of order.items||[]){const product=products.find(p=>p.id===item.id);if(!product)continue;const quantity=Math.max(1,Math.floor(Number(item.quantity)||1));const variant=product.variants?.find(v=>v.color===item.color&&v.size===item.size);if(variant&&variant.quantity>0)variant.quantity=Math.max(0,variant.quantity-quantity);else if(!product.variants?.length&&product.stock>0)product.stock=Math.max(0,product.stock-quantity);product.stock=productStock(product);changed.add(product)}if(changed.size)await CloudAPI.upsertProducts([...changed])}
$('#orderList').addEventListener('click',async event=>{const id=event.target.dataset.order,status=event.target.dataset.status;if(!id||!status)return;try{const order=orders.find(o=>o.id===id);if(status==='confirmed')await confirmAndDeduct(order);await CloudAPI.updateOrder(id,status);order.status=status;renderProducts();renderOrders();toast('订单状态已更新')}catch(error){alert(errorMessage(error))}});
$('#refreshOrders').addEventListener('click',async()=>{orders=await CloudAPI.loadOrders();renderOrders();toast('订单已刷新')});
})();
