(function(){
  'use strict';
  const $=s=>document.querySelector(s),money=(value,currency='EUR')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency}).format(Number(value)||0),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const sizeRank=['F','XS','S','M','L','XL','XXL','S/M','M/L'];let products=[],cart=[],activeProduct=null,draftQuantities=new Map();
  const form=$('#orderForm');
  function productSeason(p){const v=String(p.season||'').trim().toUpperCase();return v||(/^(65|66)\d{4}$/.test(String(p.id))?'26FW':'FW')}
  function productPrice(p){return productSeason(p)==='26FW'?(Number(p.original)||Number(p.price)||0):(Number(p.price)||Number(p.original)||0)}
  function productImage(p,color=''){return p.colorImages?.[color]||p.image||Object.values(p.colorImages||{}).find(Boolean)||''}
  function showToast(text){const t=$('#toast');t.textContent=text;t.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.hidden=true,2300)}
  function defaultOrderNumber(){const d=new Date(),part=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `PI-${part}-${String(Math.floor(Math.random()*900)+100)}`}
  function initForm(){let seller={};try{seller=JSON.parse(localStorage.getItem('interdeeSeller')||'{}')}catch(_){}form.elements.orderNumber.value=defaultOrderNumber();form.elements.orderDate.value=new Date().toISOString().slice(0,10);form.elements.sellerName.value=seller.sellerName||'DOOS';form.elements.sellerBrand.value=seller.sellerBrand||'INTERDEE';form.elements.sellerAddress.value=seller.sellerAddress||'';form.elements.sellerTaxId.value=seller.sellerTaxId||'';form.elements.sellerEmail.value=seller.sellerEmail||'interdeeparis@gmail.com'}
  async function authenticate(){try{await CloudAPI.verifyAdmin();return true}catch(_){return false}}
  async function boot(){
    if(!window.CloudAPI?.configured){$('#loginError').textContent='云端商品库尚未配置。';return}
    if(await authenticate()){showApp();await loadProducts()}
  }
  function showApp(){$('#loginView').hidden=true;$('#app').hidden=false}
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('#loginError').textContent='';try{await CloudAPI.login(e.target.email.value,e.target.password.value);await CloudAPI.verifyAdmin();showApp();await loadProducts()}catch(error){$('#loginError').textContent=error.message||'登录失败，请检查账号和密码。'}finally{btn.disabled=false}});
  async function loadProducts(){try{products=await CloudAPI.loadProducts();StoreData?.saveProducts?.(products);$('#catalogueStatus').textContent=`已同步 ${products.length} 个款号 · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}` }catch(error){products=StoreData?.getProducts?.()||[];$('#catalogueStatus').textContent=`云端同步失败，显示本机资料（${products.length} 个款号）` }buildFilters();renderProducts()}
  function buildFilters(){const seasons=[...new Set(products.map(productSeason).filter(Boolean))].sort().reverse(),categories=[...new Map(products.map(p=>[p.category,p.label||p.category])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));$('#seasonFilter').innerHTML='<option value="all">全部系列</option>'+seasons.map(x=>`<option>${esc(x)}</option>`).join('');$('#categoryFilter').innerHTML='<option value="all">全部品类</option>'+categories.map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('')}
  function renderProducts(){const q=$('#searchInput').value.trim().toLowerCase(),season=$('#seasonFilter').value,category=$('#categoryFilter').value;const list=products.filter(p=>p.visible!==false&&(season==='all'||productSeason(p)===season)&&(category==='all'||p.category===category)&&(!q||`${p.id} ${p.name} ${p.label} ${(p.variants||[]).map(v=>v.color).join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>(Number(a.order)||9999)-(Number(b.order)||9999));$('#productGrid').innerHTML=list.length?list.map(p=>{const colors=[...new Set((p.variants||[]).map(v=>v.color).filter(Boolean))],sizes=[...new Set((p.variants||[]).map(v=>v.size).filter(Boolean))],image=productImage(p),inCart=cart.filter(x=>x.reference===String(p.id)).reduce((s,x)=>s+x.quantity,0);return `<button class="product-card" type="button" data-product="${esc(p.id)}"><div class="product-card-image">${image?`<img src="${esc(image)}" alt="${esc(p.name||p.id)}" loading="lazy">`:'<span class="placeholder">INTERDEE</span>'}<i class="season-tag">${esc(productSeason(p))}</i></div><div class="product-card-body"><div class="product-card-top"><h2>${esc(p.id)}</h2><b class="product-card-price">${money(productPrice(p))}</b></div><p class="product-card-meta">${esc(p.label||p.category)} · ${esc(colors.join(', ')||'—')}</p><div class="product-card-bottom"><span>${sizes.length} 个尺码 · ${colors.length} 个颜色</span><span>${inCart?`已选 ${inCart} 件`:'点击选择'}</span></div></div></button>`}).join(''):'<div class="empty">没有找到符合条件的款号。</div>'}
  ['#searchInput','#seasonFilter','#categoryFilter'].forEach(s=>$(s).addEventListener(s==='#searchInput'?'input':'change',renderProducts));
  $('#productGrid').addEventListener('click',e=>{const card=e.target.closest('[data-product]');if(card)openProduct(card.dataset.product)});
  function openProduct(id){activeProduct=products.find(p=>String(p.id)===String(id));if(!activeProduct)return;draftQuantities=new Map();cart.filter(x=>x.reference===String(id)).forEach(x=>draftQuantities.set(`${x.color}\u0001${x.size}`,x.quantity));const variants=(activeProduct.variants||[]).filter(v=>v.color||v.size),colors=[...new Set(variants.map(v=>v.color||'—'))],sizes=[...new Set(variants.map(v=>v.size||'F'))].sort((a,b)=>(sizeRank.indexOf(a)<0?99:sizeRank.indexOf(a))-(sizeRank.indexOf(b)<0?99:sizeRank.indexOf(b)));const image=productImage(activeProduct);$('#productImage').src=image;$('#productImage').hidden=!image;$('#productPlaceholder').hidden=!!image;$('#productMeta').textContent=`${activeProduct.label||activeProduct.category||''} · ${productSeason(activeProduct)}`;$('#productTitle').textContent=activeProduct.id;$('#productPrice').textContent=money(productPrice(activeProduct));$('#productComposition').textContent=activeProduct.composition||'';$('#matrixHead').innerHTML='<tr><th>颜色 / 尺码</th>'+sizes.map(s=>`<th>${esc(s)}</th>`).join('')+'</tr>';$('#matrixBody').innerHTML=colors.map(color=>`<tr><td>${esc(color)}</td>${sizes.map(size=>{const variant=variants.find(v=>(v.color||'—')===color&&(v.size||'F')===size);if(!variant)return '<td class="variant-unavailable">—</td>';const key=`${color}\u0001${size}`,qty=draftQuantities.get(key)||0;return `<td><div class="qty-stepper" data-key="${esc(key)}" data-stock="${Number(variant.quantity)||0}"><button type="button" data-step="-1">−</button><input type="number" min="0" value="${qty}" inputmode="numeric" aria-label="${esc(color)} ${esc(size)} 数量"><button type="button" data-step="1">＋</button></div></td>`}).join('')}</tr>`).join('');updateProductSummary();$('#productDialog').showModal()}
  $('#matrixBody').addEventListener('click',e=>{const btn=e.target.closest('[data-step]');if(!btn)return;const box=btn.closest('.qty-stepper'),input=box.querySelector('input'),next=Math.max(0,Number(input.value||0)+Number(btn.dataset.step));input.value=next;draftQuantities.set(box.dataset.key,next);updateProductSummary()});
  $('#matrixBody').addEventListener('input',e=>{if(!e.target.matches('input'))return;const box=e.target.closest('.qty-stepper'),value=Math.max(0,Math.floor(Number(e.target.value)||0));e.target.value=value;draftQuantities.set(box.dataset.key,value);updateProductSummary()});
  function updateProductSummary(){const qty=[...draftQuantities.values()].reduce((s,n)=>s+Number(n||0),0);$('#productQty').textContent=qty;$('#productSubtotal').textContent=money(qty*productPrice(activeProduct))}
  $('#confirmProduct').addEventListener('click',()=>{cart=cart.filter(x=>x.reference!==String(activeProduct.id));for(const [key,quantity] of draftQuantities){if(!quantity)continue;const [color,size]=key.split('\u0001');cart.push({reference:String(activeProduct.id),name:activeProduct.name||activeProduct.id,category:activeProduct.label||activeProduct.category||'',composition:activeProduct.composition||'',color,size,quantity:Number(quantity),unitPrice:productPrice(activeProduct),image:productImage(activeProduct,color)})}saveDraft();updateCart();$('#productDialog').close();renderProducts();showToast('已加入订单')});
  function saveDraft(){localStorage.setItem('interdeeOrderDraft',JSON.stringify({cart,form:Object.fromEntries(new FormData(form))}))}
  function restoreDraft(){try{const d=JSON.parse(localStorage.getItem('interdeeOrderDraft')||'null');if(!d?.cart?.length)return;cart=d.cart;if(d.form)Object.entries(d.form).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});updateCart()}catch(_){}}
  function updateCart(){const qty=cart.reduce((s,x)=>s+x.quantity,0),total=cart.reduce((s,x)=>s+x.quantity*x.unitPrice,0),currency=form.elements.currency?.value||'EUR';$('#cartCount').textContent=qty;$('#cartTotal').textContent=money(total,currency);$('#totalQty').textContent=qty;$('#grandTotal').textContent=money(total,currency)}
  function renderOrder(){const currency=form.elements.currency.value;$('#orderLines').innerHTML=cart.length?cart.map((x,i)=>`<article class="order-line" data-index="${i}">${x.image?`<img src="${esc(x.image)}" alt="">`:'<span></span>'}<div><strong>${esc(x.reference)}</strong><small>${esc(x.category)}</small></div><div class="variant"><strong>${esc(x.color)}</strong><small>${esc(x.size)}</small></div><label>数量<input data-field="quantity" type="number" min="1" step="1" value="${x.quantity}" inputmode="numeric"></label><label class="price">单价<input data-field="unitPrice" type="number" min="0" step="0.01" value="${Number(x.unitPrice).toFixed(2)}"></label><button class="remove-line" data-remove type="button" aria-label="删除">×</button><div class="line-total">${money(x.quantity*x.unitPrice,currency)}</div></article>`).join(''):'<div class="order-empty">订单还是空的，请先点击款号录入数量。</div>';updateCart()}
  $('#openOrderButton').addEventListener('click',()=>{renderOrder();$('#orderDialog').showModal()});
  $('#orderLines').addEventListener('input',e=>{const line=e.target.closest('[data-index]');if(!line)return;const item=cart[Number(line.dataset.index)],field=e.target.dataset.field;if(field==='quantity')item.quantity=Math.max(1,Math.floor(Number(e.target.value)||1));if(field==='unitPrice')item.unitPrice=Math.max(0,Number(e.target.value)||0);line.querySelector('.line-total').textContent=money(item.quantity*item.unitPrice,form.elements.currency.value);saveDraft();updateCart()});
  $('#orderLines').addEventListener('click',e=>{const btn=e.target.closest('[data-remove]');if(!btn)return;cart.splice(Number(btn.closest('[data-index]').dataset.index),1);saveDraft();renderOrder();renderProducts()});
  form.addEventListener('input',()=>{saveDraft();updateCart()});form.elements.currency.addEventListener('change',renderOrder);
  function collect(){const values=Object.fromEntries(new FormData(form));return {...values,lines:cart.map(x=>({...x})),currency:values.currency||'EUR'}}
  function validate(){if(!cart.length){showToast('请先添加商品');return false}if(!form.reportValidity())return false;const seller=['sellerName','sellerBrand','sellerAddress','sellerTaxId','sellerEmail'].reduce((o,k)=>(o[k]=form.elements[k].value,o),{});localStorage.setItem('interdeeSeller',JSON.stringify(seller));return true}
  $('#excelButton').addEventListener('click',async e=>{if(!validate())return;e.target.disabled=true;try{await ProformaExport.excel(collect());showToast('Excel 已生成')}catch(error){alert(error.message)}finally{e.target.disabled=false}});
  $('#pdfButton').addEventListener('click',async e=>{if(!validate())return;e.target.disabled=true;try{await ProformaExport.pdf(collect());showToast('PDF Proforma 已生成')}catch(error){alert(error.message)}finally{e.target.disabled=false}});
  $('#saveOnlineButton').addEventListener('click',async e=>{if(!validate())return;e.target.disabled=true;$('#saveStatus').textContent='正在保存…';const d=collect(),customer={name:d.customerName,customerCode:d.customerCode,vatNumber:d.vatNumber,billingAddress:d.billingAddress,email:d.email,phone:d.phone,note:d.note,orderNumber:d.orderNumber,orderDate:d.orderDate,season:d.season,delivery:d.delivery,paymentTerms:d.paymentTerms,currency:d.currency};const items=d.lines.map(x=>({id:x.reference,name:x.name,color:x.color,size:x.size,quantity:x.quantity,price:x.unitPrice,lineTotal:x.quantity*x.unitPrice,category:x.category,composition:x.composition})),total=items.reduce((s,x)=>s+x.lineTotal,0);try{const saved=await CloudAPI.submitOrder(customer,items,total);$('#saveStatus').textContent=`已保存到后台：${saved.public_code||saved.id}`;showToast('订单已保存')}catch(error){$('#saveStatus').textContent=error.message||'保存失败'}finally{e.target.disabled=false}});
  function newOrder(){cart=[];localStorage.removeItem('interdeeOrderDraft');form.reset();initForm();updateCart();renderProducts();$('#orderDialog').close();showToast('已新建空白订单')}
  $('#newOrderButton').addEventListener('click',()=>{if(cart.length&&!confirm('当前订单尚未清空，确定新建订单吗？'))return;newOrder()});$('#clearOrderButton').addEventListener('click',()=>{if(cart.length&&!confirm('确定清空当前订单吗？'))return;cart=[];saveDraft();renderOrder();renderProducts()});
  document.addEventListener('click',e=>{const btn=e.target.closest('[data-close]');if(btn)document.getElementById(btn.dataset.close)?.close()});
  initForm();restoreDraft();boot();
}());
